In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
ls

 Volume in drive C is OS
 Volume Serial Number is 3041-72E3

 Directory of C:\Users\StevenJBark\Desktop\RICEDAV\Projects\RiceBootcampProject1\Team10Project1_Repo\rawdata

11/14/2019  08:59 PM    <DIR>          .
11/14/2019  08:59 PM    <DIR>          ..
11/14/2019  07:56 PM                 1 .gitkeep
11/14/2019  08:02 PM    <DIR>          .ipynb_checkpoints
11/14/2019  08:53 PM            12,910 Categories_of_Interest_FY19_g05_STAAR_Data.txt
11/14/2019  07:56 PM        26,639,647 cfy19e5.csv
11/14/2019  08:59 PM             1,788 FinalHeaders.csv
11/14/2019  07:56 PM           550,912 fy19_varlist_g05.csv
11/14/2019  08:59 PM            94,534 SchoolData_Focused.ipynb
11/14/2019  08:01 PM             4,521 Untitled.ipynb
               7 File(s)     27,304,313 bytes
               3 Dir(s)  441,360,277,504 bytes free

In [32]:
headers = pd.read_csv('FinalHeaders.csv', header=0)
headers.head(10)

       ColumnHeaders
0             CAMPUS
1              DNAME
2              CNAME
3              GRADE
4   m_all_unsatgl_nm
5  m_sexm_unsatgl_nm
6  m_sexf_unsatgl_nm
7  m_ethh_unsatgl_nm
8  m_ethi_unsatgl_nm
9  m_etha_unsatgl_nm

In [33]:
headerlist = []

for index, row in headers.iterrows():
    headerlist.append(row[0])

headerlist

['CAMPUS',
 'DNAME',
 'CNAME',
 'GRADE',
 'm_all_unsatgl_nm',
 'm_sexm_unsatgl_nm',
 'm_sexf_unsatgl_nm',
 'm_ethh_unsatgl_nm',
 'm_ethi_unsatgl_nm',
 'm_etha_unsatgl_nm',
 'm_ethb_unsatgl_nm',
 'm_ethp_unsatgl_nm',
 'm_ethw_unsatgl_nm',
 'm_ecoy_unsatgl_nm',
 'm_econ_unsatgl_nm',
 'm_eco1_unsatgl_nm',
 'm_eco2_unsatgl_nm',
 'm_eco9_unsatgl_nm',
 'm_ti19_unsatgl_nm',
 'm_migy_unsatgl_nm',
 'm_mign_unsatgl_nm',
 'm_spey_unsatgl_nm',
 'm_spen_unsatgl_nm',
 'm_gify_unsatgl_nm',
 'm_gifn_unsatgl_nm',
 'm_atry_unsatgl_nm',
 'm_atrn_unsatgl_nm',
 'm_all_approgl_nm',
 'm_sexm_approgl_nm',
 'm_sexf_approgl_nm',
 'm_ethh_approgl_nm',
 'm_ethi_approgl_nm',
 'm_etha_approgl_nm',
 'm_ethb_approgl_nm',
 'm_ethp_approgl_nm',
 'm_ethw_approgl_nm',
 'm_ecoy_approgl_nm',
 'm_econ_approgl_nm',
 'm_eco1_approgl_nm',
 'm_eco2_approgl_nm',
 'm_eco9_approgl_nm',
 'm_ti19_approgl_nm',
 'm_migy_approgl_nm',
 'm_mign_approgl_nm',
 'm_spey_approgl_nm',
 'm_spen_approgl_nm',
 'm_gify_approgl_nm',
 'm_gifn_approgl_nm',
 'm_atry_approgl_nm',
 'm_atrn_approgl_nm',
 'm_all_meetsgl_nm',
 'm_sexm_meetsgl_nm',
 'm_sexf_meetsgl_nm',
 'm_ethh_meetsgl_nm',
 'm_ethi_meetsgl_nm',
 'm_etha_meetsgl_nm',
 'm_ethb_meetsgl_nm',
 'm_ethp_meetsgl_nm',
 'm_ethw_meetsgl_nm',
 'm_ecoy_meetsgl_nm',
 'm_econ_meetsgl_nm',
 'm_eco1_meetsgl_nm',
 'm_eco2_meetsgl_nm',
 'm_eco9_meetsgl_nm',
 'm_ti19_meetsgl_nm',
 'm_migy_meetsgl_nm',
 'm_mign_meetsgl_nm',
 'm_spey_meetsgl_nm',
 'm_spen_meetsgl_nm',
 'm_gify_meetsgl_nm',
 'm_gifn_meetsgl_nm',
 'm_atry_meetsgl_nm',
 'm_atrn_meetsgl_nm',
 'm_all_mastrgl_nm',
 'm_sexm_mastrgl_nm',
 'm_sexf_mastrgl_nm',
 'm_ethh_mastrgl_nm',
 'm_ethi_mastrgl_nm',
 'm_etha_mastrgl_nm',
 'm_ethb_mastrgl_nm',
 'm_ethp_mastrgl_nm',
 'm_ethw_mastrgl_nm',
 'm_ecoy_mastrgl_nm',
 'm_econ_mastrgl_nm',
 'm_eco1_mastrgl_nm',
 'm_eco2_mastrgl_nm',
 'm_eco9_mastrgl_nm',
 'm_ti19_mastrgl_nm',
 'm_migy_mastrgl_nm',
 'm_mign_mastrgl_nm',
 'm_spey_mastrgl_nm',
 'm_spen_mastrgl_nm',
 'm_gify_mastrgl_nm',
 'm_gifn_mastrgl_nm',
 'm_atry_mastrgl_nm',
 'm_atrn_mastrgl_nm']

In [34]:
schooldata_df = pd.read_csv('cfy19e5.csv', header=0)
schooldata_df.head()

,CAMPUS,YEAR,REGION,DISTRICT,DNAME,CNAME,GRADE,r_all_docs_n,r_all_abs_n,r_all_oth_n,...,s_gifn_avg_cat4,s_gifn_pct_cat4,s_gifv_avg_cat4,s_gifv_pct_cat4,s_atry_avg_cat4,s_atry_pct_cat4,s_atrn_avg_cat4,s_atrn_pct_cat4,s_atrv_avg_cat4,s_atrv_pct_cat4
0,1902103,19,7,1902,CAYUGA ISD,CAYUGA ELEM.,5,48,0,0,...,9.3,78.0,NaN,NaN,8.5,71.0,10.7,89.0,NaN,
1,1903102,19,7,1903,ELKHART ISD,ELKHART INTERME,5,83,0,0,...,9.3,77.0,NaN,NaN,7.8,65.0,10.3,85.0,NaN,
2,1904102,19,7,1904,FRANKSTON ISD,FRANKSTON ELEM.,5,60,0,1,...,9.1,76.0,NaN,NaN,7.6,63.0,10.1,84.0,NaN,
3,1906102,19,7,1906,NECHES ISD,NECHES ELEM.,5,24,0,0,...,8.9,74.0,NaN,NaN,8.1,68.0,9.6,80.0,NaN,
4,1907110,19,7,1907,PALESTINE ISD,STORY INTERMEDI,5,243,0,0,...,7.8,65.0,NaN,NaN,6.9,58.0,9.7,81.0,NaN,

In [35]:
cleanedschooldata = schooldata_df[headerlist]

In [36]:
cleanedschooldata

,CAMPUS,DNAME,CNAME,GRADE,m_all_unsatgl_nm,m_sexm_unsatgl_nm,m_sexf_unsatgl_nm,m_ethh_unsatgl_nm,m_ethi_unsatgl_nm,m_etha_unsatgl_nm,...,m_eco9_mastrgl_nm,m_ti19_mastrgl_nm,m_migy_mastrgl_nm,m_mign_mastrgl_nm,m_spey_mastrgl_nm,m_spen_mastrgl_nm,m_gify_mastrgl_nm,m_gifn_mastrgl_nm,m_atry_mastrgl_nm,m_atrn_mastrgl_nm
0,1902103,CAYUGA ISD,CAYUGA ELEM.,5,4.0,2.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,29.0,1.0,28.0,5.0,24.0,15.0,14.0
1,1903102,ELKHART ISD,ELKHART INTERME,5,3.0,2.0,1.0,0.0,NaN,NaN,...,NaN,NaN,NaN,43.0,2.0,41.0,4.0,39.0,5.0,38.0
2,1904102,FRANKSTON ISD,FRANKSTON ELEM.,5,7.0,5.0,2.0,0.0,NaN,NaN,...,NaN,NaN,NaN,26.0,0.0,26.0,NaN,24.0,3.0,23.0
3,1906102,NECHES ISD,NECHES ELEM.,5,1.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,NaN,10.0,NaN,8.0,0.0,10.0
4,1907110,PALESTINE ISD,STORY INTERMEDI,5,58.0,29.0,29.0,27.0,NaN,NaN,...,NaN,NaN,NaN,51.0,0.0,51.0,6.0,45.0,15.0,36.0
5,1908101,WESTWOOD ISD,WESTWOOD ELEM.,5,43.0,21.0,22.0,12.0,NaN,NaN,...,NaN,NaN,NaN,22.0,0.0,22.0,NaN,21.0,6.0,16.0
6,1909101,SLOCUM ISD,SLOCUM PRE-K -,5,3.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,NaN,5.0,NaN,3.0,1.0,4.0
7,2901104,ANDREWS ISD,UNDERWOOD ELEM.,5,97.0,47.0,50.0,71.0,NaN,NaN,...,NaN,NaN,NaN,74.0,1.0,73.0,19.0,55.0,6.0,68.0
8,3801103,PINEYWOODS COMM,SARAH STRINDEN,5,5.0,4.0,1.0,3.0,NaN,NaN,...,NaN,NaN,NaN,35.0,0.0,35.0,8.0,27.0,7.0,28.0
9,3902102,HUDSON ISD,W.H. BONNER ELE,5,7.0,2.0,5.0,0.0,NaN,NaN,...,NaN,NaN,NaN,121.0,2.0,119.0,13.0,108.0,28.0,93.0
10,3903120,LUFKIN ISD,ANDERSON ELEM.,5,14.0,8.0,6.0,5.0,NaN,NaN,...,NaN,NaN,NaN,30.0,2.0,28.0,NaN,30.0,10.0,20.0
11,3903121,LUFKIN ISD,BRANDON ELEM.,5,35.0,21.0,14.0,4.0,NaN,NaN,...,NaN,NaN,NaN,50.0,0.0,50.0,42.0,8.0,4.0,46.0
12,3903122,LUFKIN ISD,BROOKHOLLOW ELE,5,23.0,13.0,10.0,5.0,NaN,NaN,...,NaN,NaN,NaN,28.0,1.0,27.0,NaN,28.0,3.0,25.0
13,3903123,LUFKIN ISD,COSTON ELEM.,5,12.0,8.0,4.0,6.0,NaN,NaN,...,NaN,NaN,NaN,38.0,0.0,38.0,NaN,38.0,18.0,20.0
14,3903129,LUFKIN ISD,SLACK ELEM.,5,44.0,23.0,21.0,30.0,NaN,NaN,...,NaN,NaN,NaN,35.0,1.0,34.0,NaN,35.0,7.0,28.0
15,3904102,HUNTINGTON ISD,HUNTINGTON INTE,5,12.0,5.0,7.0,2.0,NaN,NaN,...,NaN,NaN,NaN,40.0,2.0,38.0,NaN,36.0,10.0,30.0
16,3905103,DIBOLL ISD,H.G. TEMPLE INT,5,26.0,14.0,12.0,13.0,NaN,NaN,...,NaN,NaN,NaN,33.0,0.0,33.0,NaN,29.0,13.0,20.0
17,3906101,ZAVALLA ISD,ZAVALLA ELEM.,5,3.0,1.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,7.0,NaN,7.0,NaN,5.0,1.0,6.0
18,3907041,CENTRAL ISD,CENTRAL JR.H.,5,24.0,12.0,12.0,5.0,NaN,NaN,...,NaN,NaN,NaN,23.0,0.0,23.0,3.0,20.0,2.0,21.0
19,4901101,ARANSAS COUNTY,FULTON LEARNING,5,71.0,34.0,37.0,37.0,NaN,0.0,...,NaN,NaN,NaN,62.0,1.0,61.0,20.0,42.0,14.0,48.0
20,5901101,ARCHER CITY ISD,ARCHER CITY ELE,5,1.0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,15.0,NaN,15.0,NaN,13.0,1.0,14.0
21,5902101,HOLLIDAY ISD,HOLLIDAY ELEM.,5,9.0,4.0,5.0,1.0,NaN,NaN,...,NaN,NaN,NaN,42.0,1.0,41.0,7.0,35.0,3.0,39.0
22,5904101,WINDTHORST ISD,WINDTHORST ELEM,5,1.0,1.0,0.0,1.0,NaN,NaN,...,NaN,NaN,NaN,15.0,NaN,15.0,NaN,12.0,1.0,14.0
23,6902101,CLAUDE ISD,CLAUDE ELEM.,5,0.0,0.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,16.0,NaN,16.0,NaN,12.0,2.0,14.0
24,7901041,CHARLOTTE ISD,CHARLOTTE M.S.,5,14.0,9.0,5.0,14.0,NaN,NaN,...,NaN,NaN,NaN,5.0,1.0,4.0,NaN,4.0,3.0,2.0
25,7902101,JOURDANTON ISD,JOURDANTON ELEM,5,34.0,17.0,17.0,21.0,NaN,NaN,...,NaN,NaN,NaN,25.0,0.0,25.0,5.0,20.0,2.0,23.0
26,7904101,LYTLE ISD,LYTLE ELEM.,5,30.0,17.0,13.0,29.0,NaN,NaN,...,NaN,NaN,NaN,35.0,0.0,35.0,5.0,30.0,10.0,25.0
27,7905103,PLEASANTON ISD,PLEASANTON ELEM,5,85.0,43.0,42.0,60.0,NaN,NaN,...,NaN,NaN,NaN,47.0,3.0,44.0,11.0,36.0,9.0,38.0
28,7906102,POTEET ISD,POTEET INTERMED,5,29.0,17.0,12.0,22.0,NaN,NaN,...,NaN,NaN,NaN,32.0,0.0,32.0,7.0,25.0,5.0,27.0
29,8901102,BELLVILLE ISD,O'BRYANT INTERM,5,25.0,17.0,8.0,14.0,NaN,NaN,...,NaN,NaN,NaN,39.0,1.0,38.0,14.0,25.0,2.0,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4296,247903002,LA VERNIA ISD,FLORESVILLE ALT,5,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4297,247903104,LA VERNIA ISD,LA VERNIA INTER,5,4.0,1.0,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,138.0,4.0,134.0,22.0,116.0,19.0,119.0
4298,247904101,POTH ISD,POTH ELEM.,5,2.0,1.0,1.0,2.0,NaN,NaN,...,NaN,NaN,NaN,30.0,0.0,30.0,NaN,27.0,3.0,27.0
4299,247906101,STOCKDALE ISD,STOCKDALE ELEM.,5,3.0,2.0,1.0,2.0,NaN,NaN,...,NaN,NaN,NaN,19.0,0.0,19.0,10.0,9.0,2.0,17.0
4300,248901041,KERMIT ISD,KERMIT JR.H.,5,64.0,31.0,33.0,47.0,NaN,NaN,...,0.0,NaN,NaN,9.0,0.0,9.0,0.0,9.0,3.0,6.0
4301,248902101,WINK-LOVING ISD,WINK ELEM.,5,13.0,10.0,3.0,8.0,NaN,NaN,...,NaN,NaN,NaN,10.0,0.0,10.0,NaN,10.0,0.0,10.0
4302,249901101,ALVORD ISD,ALVORD ELEM.,5,4.0,1.0,3.0,1.0,NaN,NaN,...,NaN,NaN,NaN,24.0,1.0,23.0,NaN,21.0,7.0,17.0
4303,249902110,BOYD ISD,BOYD INTERMEDIA,5,14.0,6.0,8.0,3.0,NaN,NaN,...,NaN,NaN,NaN,24.0,0.0,24.0,5.0,19.0,5.0,19.0
4304,249903102,BRIDGEPORT ISD,BRIDGEPORT INTE,5,37.0,18.0,19.0,18.0,NaN,NaN,...,NaN,NaN,NaN,37.0,1.0,36.0,7.0,30.0,6.0,31.0
4305,249904101,CHICO ISD,CHICO ELEM.,5,12.0,2.0,10.0,6.0,NaN,NaN,...,NaN,NaN,NaN,11.0,NaN,11.0,5.0,6.0,1.0,10.0
4306,249905105,DECATUR ISD,DECATUR INTERME,5,33.0,19.0,14.0,10.0,NaN,0.0,...,NaN,NaN,NaN,83.0,4.0,79.0,27.0,56.0,24.0,59.0
4307,249906050,PARADISE ISD,PARADISE INTERM,5,4.0,1.0,3.0,0.0,NaN,NaN,...,NaN,NaN,NaN,47.0,2.0,45.0,18.0,29.0,4.0,43.0
4308,249908001,SLIDELL ISD,SLIDELL SCHOOLS,5,7.0,4.0,3.0,5.0,NaN,NaN,...,NaN,NaN,NaN,11.0,NaN,11.0,NaN,10.0,3.0,8.0
4309,250902101,HAWKINS ISD,HAWKINS ELEM.,5,2.0,0.0,2.0,NaN,NaN,NaN,...,NaN,NaN,NaN,28.0,NaN,27.0,10.0,18.0,8.0,20.0
4310,250903102,MINEOLA ISD,MINEOLA ELEM.,5,35.0,16.0,19.0,13.0,NaN,NaN,...,NaN,NaN,NaN,26.0,0.0,26.0,NaN,24.0,5.0,21.0
4311,250904101,QUITMAN ISD,QUITMAN ELEM.,5,3.0,1.0,2.0,0.0,NaN,NaN,...,NaN,NaN,NaN,14.0,NaN,14.0,4.0,10.0,0.0,14.0
4312,250905101,YANTIS ISD,YANTIS ELEM.,5,6.0,3.0,3.0,2.0,NaN,NaN,...,NaN,NaN,NaN,6.0,NaN,6.0,NaN,5.0,1.0,5.0
4313,250906101,ALBA-GOLDEN ISD,ALBA-GOLDEN ELE,5,5.0,3.0,2.0,2.0,NaN,NaN,...,NaN,NaN,NaN,15.0,0.0,15.0,NaN,12.0,3.0,12.0
4314,250907041,WINNSBORO ISD,MEMORIAL M.S.,5,14.0,12.0,2.0,4.0,NaN,NaN,...,NaN,NaN,NaN,36.0,1.0,35.0,NaN,34.0,3.0,33.0
4315,251901101,DENVER CITY ISD,KELLEY ELEM.,5,24.0,13.0,11.0,21.0,NaN,NaN,...,NaN,NaN,NaN,47.0,1.0,46.0,12.0,35.0,3.0,44.0
4316,251902101,PLAINS ISD,PLAINS ELEM.,5,23.0,12.0,11.0,22.0,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,3.0,NaN,2.0,0.0,3.0
4317,252901105,GRAHAM ISD,GRAHAM ELEM.,5,48.0,20.0,28.0,16.0,NaN,NaN,...,NaN,NaN,NaN,36.0,2.0,34.0,5.0,31.0,20.0,16.0
4318,252902002,NEWCASTLE ISD,NEWCASTLE SCHOO,5,4.0,3.0,1.0,1.0,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,4.0,NaN,4.0,3.0,1.0
4319,252903101,OLNEY ISD,OLNEY ELEM.,5,3.0,1.0,2.0,0.0,NaN,NaN,...,NaN,NaN,NaN,30.0,1.0,29.0,7.0,23.0,5.0,25.0
4320,253901101,ZAPATA COUNTY I,BENAVIDES ELEM.,5,0.0,0.0,0.0,0.0,NaN,NaN,...,NaN,NaN,NaN,7.0,NaN,7.0,NaN,7.0,2.0,5.0
4321,253901105,ZAPATA COUNTY I,ZAPATA NORTH EL,5,17.0,12.0,5.0,17.0,NaN,NaN,...,3.0,NaN,NaN,23.0,0.0,23.0,6.0,17.0,7.0,16.0
4322,253901106,ZAPATA COUNTY I,ZAPATA SOUTH EL,5,18.0,13.0,5.0,18.0,NaN,NaN,...,8.0,NaN,NaN,21.0,0.0,21.0,8.0,13.0,10.0,11.0
4323,253901107,ZAPATA COUNTY I,FIDEL AND ANDRE,5,8.0,7.0,1.0,8.0,NaN,NaN,...,10.0,NaN,NaN,37.0,4.0,33.0,NaN,34.0,23.0,14.0
4324,254901104,CRYSTAL CITY IS,BENITO JUAREZ M,5,69.0,38.0,31.0,67.0,NaN,NaN,...,2.0,NaN,0.0,12.0,0.0,12.0,5.0,7.0,1.0,11.0
4325,254902101,LA PRYOR ISD,LA PRYOR ELEM.,5,7.0,5.0,2.0,7.0,NaN,NaN,...,NaN,NaN,NaN,9.0,NaN,9.0,NaN,6.0,3.0,6.0

In [37]:
cleanedschooldata.to_csv('CleanedSchoolData.csv', header=True, index=False)