In [2]:
#Import dependencies and modules
import pandas as pd
import numpy as np
import scipy.stats as sp
import matplotlib.pyplot as plt

In [3]:
#Open demographics data, Grade 3
demographics3 = pd.read_csv('../cleandata/DemographicsHABWGrade3.csv', header=0)
demographics3.head()

,CAMPUS,DNAME,CNAME,GRADE,District Type,School Site Street Address,School Site City,School Site Zip,Below Grade Level Hispanic,Below Grade Level Asian,...,Approach Grade Level Black,Approach Grade Level White,Meet Grade Level Hispanic,Meet Grade Level Asian,Meet Grade Level Black,Meet Grade Level White,Master Grade Level Hispanic,Master Grade Level Asian,Master Grade Level Black,Master Grade Level White
0,1902103,CAYUGA ISD,CAYUGA ELEM.,3,INDEPENDENT,17750 N US HWY 287,TENNESSEE COLONY,75861,0.0,0.0,...,0.0,34.0,0.0,0.0,0.0,32.0,0.0,0.0,0.0,22.0
1,1903102,ELKHART ISD,ELKHART INTERME,3,INDEPENDENT,301 E PARKER ST,ELKHART,75839-9701,4.0,0.0,...,2.0,58.0,4.0,0.0,0.0,33.0,1.0,0.0,0.0,11.0
2,1904102,FRANKSTON ISD,FRANKSTON ELEM.,3,INDEPENDENT,100 PERRY ST,FRANKSTON,75763-0428,1.0,0.0,...,2.0,30.0,3.0,0.0,1.0,21.0,1.0,0.0,0.0,8.0
3,1906102,NECHES ISD,NECHES ELEM.,3,INDEPENDENT,3055 FM 2574,PALESTINE,75803,1.0,0.0,...,0.0,15.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,2.0
4,1907107,PALESTINE ISD,SOUTHSIDE ELEM.,3,INDEPENDENT,201 GILLESPIE RD,PALESTINE,75801-7627,14.0,0.0,...,39.0,51.0,39.0,0.0,16.0,33.0,23.0,0.0,8.0,17.0

In [7]:
#For data processing across rows, create a new dataframe with only the number data and district type
demographics3.columns

Index(['CAMPUS', 'DNAME', 'CNAME', 'GRADE', 'District Type',
       'School Site Street Address', 'School Site City', 'School Site Zip',
       'Below Grade Level Hispanic', 'Below Grade Level Asian',
       'Below Grade Level Black', 'Below Grade Level White',
       'Approach Grade Level Hispanic', 'Approach Grade Level Asian',
       'Approach Grade Level Black', 'Approach Grade Level White',
       'Meet Grade Level Hispanic', 'Meet Grade Level Asian',
       'Meet Grade Level Black', 'Meet Grade Level White',
       'Master Grade Level Hispanic', 'Master Grade Level Asian',
       'Master Grade Level Black', 'Master Grade Level White'],
      dtype='object')

In [ ]:
demographics3(['DNAME', 'CNAME', 'District Type',
       
       'Below Grade Level Hispanic', 'Below Grade Level Asian',
       'Below Grade Level Black', 'Below Grade Level White',
       'Approach Grade Level Hispanic', 'Approach Grade Level Asian',
       'Approach Grade Level Black', 'Approach Grade Level White',
       'Meet Grade Level Hispanic', 'Meet Grade Level Asian',
       'Meet Grade Level Black', 'Meet Grade Level White',
       'Master Grade Level Hispanic', 'Master Grade Level Asian',
       'Master Grade Level Black', 'Master Grade Level White'])